server: 
    port: 8181 
spring:
    application:
        name: api-hyperledger-fabric-spring


# configuration about the network that we are working with 
fabric:
    network:
        channel: mychannel
        discovery: true # enable the service-discover in fabric (allow client(application) to connect with fabric)
        # this is the connection to our fabric file path
        config-path:


    ca: